### PR TITLE
update print statement for py3+

### PR DESCRIPTION
**Pull request by johannjacobsohn**

### CODE REVIEW

**Comment by Pezmc** [comment]
What issue were you seeing? This script is supposed to be both 3 & 2 compatible

Does this new format work with both?

**Comment by Flowdalic** [comment]
> Does this new format work with both?

No it does not work on Python 3: [`print >>` is a Python 2 only idiom](https://stackoverflow.com/questions/34385674/what-does-print-do-in-python). I would recommend that you use `2to3` to update the script to Python 3.

**Comment by Pezmc** [comment]
Thanks for confirming, closing as this script is both Python 3 and Python 2 compatible; if Python 3 drops support for this syntax, we'll need to migrate to Python 3 only!

**Comment by Flowdalic** [comment]
> closing as this script is both Python 3 and Python 2 compatible

I think you misunderstood something. The script, as of now, is *not* Python 3 compatible, because it uses `print >>`.

**Comment by Pezmc** [comment]
@Flowdalic Good point, I think we're talking past each other, I asked if the new format in the PR is Python 2 compatible, you answered, that it doesn't work in Python 3. Reading back, I was talking about `print` you were talking about `>>`!

**Comment by Flowdalic** [comment]
> I asked if the new format in the PR is Python 2 compatible, you answered, that it doesn't work in Python 3.

Ha, right. Sorry for the confusion.

**Pull request merged**
