### PR TITLE
add the default aux and output for the opotional -o -a options

### PR DESCRIPTION
**Pull request by hushidong**
Sometimes we need to check all the entries in the bib file other than
the referenced entries in aux file, so we can add some code to deal for
the omitted aux file and omitted output file specifications.

### CODE REVIEW

**Comment by Pezmc** [comment]
Hi @hushidong,

Thanks for your contribution!

Today, by default, we don't output an `html` file unless requested, I don't think we should be changing this behaviour for all users. To get the same functionality as you've added in this PR use: `-i input.bib -o input.bib.html`.

For "check all the entries in the bib file" functionality, that's exactly what happens by default if no aux file is found. That leaves `usedIds` as an empty set, and later on the script includes all entries by default if `userIds` [is empty](https://github.com/Pezmc/BibLatex-Check/pull/41/files#diff-896bb79242c63e993df5b2b1cef994f4L180) `if currentId in usedIds or not usedIds:`. To get this functionality, only define an input file `-i input.bib`.

Therefore, unfortunately, at this time I'm going to close this PR, let me know if you have any other suggestions!

**Comment by hushidong** [comment]
sorry for my noise, 
 I have not found the -i option in the readme file

**Comment by Pezmc** [comment]
No problem, if you find any thing else missing from the readme please do open a PR to fix/update it!

**Comment by hushidong** [comment]
OK，thanks

**Pull request closed without merging**
